# Configuration of detekt rule sets, see https://arturbosch.github.io/detekt/comments.html.
# This file only lists the differences to the default configuration at
# https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml.

build:
  maxIssues: 0
  weights:
    comments: 0

complexity:
  ComplexMethod:
    threshold: 20
  LargeClass:
    threshold: 150
  LongMethod:
    threshold: 80
  LongParameterList:
    threshold: 8
  NestedBlockDepth:
    threshold: 5
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInObjects: 15

formatting:
  NoItParamInMultilineLambda:
    active: false
  # This is a ktlint plugin rule: As it does not allow exceptions, we need to disable it.
  NoWildcardImports:
    active: false
  # This is a ktlint plugin rule: As it clashes with the official Kotlin coding conventions, we need to disable it.
  ParameterListWrapping:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  UnusedImports:
    active: true
  WildcardImport:
    excludeImports: '
      ch.frankel.slf4k.*,
      com.here.ort.analyzer.managers.*,
      com.here.ort.commands.*,
      com.here.ort.downloader.vcs.*,
      com.here.ort.reporter.reporters.*,
      com.here.ort.scanner.scanners.*,
      com.here.ort.spdx.SpdxLicense.*,
      com.here.ort.spdx.SpdxLicenseException.*,
      kotlinx.html.*,
      kotlinx.html.dom.*
      '
