# This image is based on Alpine Linux 3.9 with alpine-pkg-glibc and Oracle JDK 8 installed.
FROM frolvlad/alpine-java:jdk8.202.08-slim

# Required to run the "funTest" tasks.
RUN wget -q -O /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo \
    && chmod a+x /usr/local/bin/repo
RUN apk add --no-cache bash dep npm python2 python3 py-pip ruby-bundler ruby-rdoc ruby-rugged \
    && npm install -g bower \
    && gem install licensee \
    && pip install scancode-toolkit
